const CONFIG = {
  STRIPE_PUBLIC_KEY: window._RNS_STRIPE || '',
  SUPABASE_URL: window._RNS_SB_URL || '',
  SUPABASE_ANON_KEY: window._RNS_SB_KEY || '',
  EMAILJS_PUBLIC_KEY: '',
  EMAILJS_SERVICE_ID: '',
  EMAILJS_TEMPLATE_ID: '',
};
